// ═══════════════════════════════════════════════════════════
// DATA & CONSTANTS
// ═══════════════════════════════════════════════════════════

export const CATEGORIES = [
  { id:'lager',      name:'Lager',              color:'#D4A017' },
  { id:'ale',        name:'Ale',                color:'#D4882E' },
  { id:'ipa',        name:'IPA',                color:'#6B8F3E' },
  { id:'stout',      name:'Stout & Porter',     color:'#A08060' },
  { id:'weizen',     name:'Weizen & Blanche',   color:'#C8A84B' },
  { id:'sour',       name:'Sour & Lambic',      color:'#B5A014' },
  { id:'trappist',   name:'Trappista & Abbey',  color:'#8B4513' },
  { id:'pilsner',    name:'Pilsner',             color:'#C8B400' },
  { id:'saison',     name:'Saison & Farmhouse', color:'#D4A856' },
  { id:'barleywine', name:'Barleywine',         color:'#8B2020' },
  { id:'radler',     name:'Radler & Shandy',    color:'#E8952E' },
  { id:'other',      name:'Altro',              color:'#9E7B5A' },
];

export const CAT_MAP = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));

export const SAMPLE_BEERS = [
  { name:'Kalopsia', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.6, ibu:40,
    origin:'Varese, Italia', color:'Ambrata chiara limpida, testa bianca cremosa',
    description:'APA (American Pale Ale) flagship del birrificio. Luppoli americani Cascade e Centennial donano classici aromi di pompelmo, resina e fiori d\'arancio. Maltatura caramellata presente ma discreta, a supporto dell\'amaro bilanciato e persistente.',
    history:'"Kalopsia" in greco antico significa "visione distorta di bellezza". È la birra che ha lanciato il birrificio: con oltre 300 recensioni entusiaste è diventata l\'identità di 50&50, una piccola grande ossessione varesina.',
    tried:false, favorite:false, notes:'' },
  { name:'Danko', brewery:'50&50 Craft Brewery', category:'stout', rating:0, abv:8.0, ibu:25,
    origin:'Varese, Italia', color:'Nero profondo con riflessi bruni, testa beige compatta',
    description:'Baltic Porter di forza e complessità notevoli. Aromi intensi di cioccolato fondente, caffè espresso, frutta sotto spirito e tabacco. La fermentazione lager garantisce una pulizia straordinaria. Alcol perfettamente integrato. Corpo pieno e vellutato.',
    history:'"Danko" omaggia il personaggio mitologico slavo che strappò il proprio cuore ardente dal petto per illuminare il cammino del suo popolo. Media di 4.86/5: la birra più amata del catalogo.',
    tried:false, favorite:false, notes:'' },
  { name:'United', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.8, ibu:40,
    origin:'Varese, Italia', color:'Ambrata dorata brillante, testa bianca compatta',
    description:'DDH West Coast IPA prodotta con doppio dry-hopping. L\'intensità aromatica è notevole: agrumi, frutta tropicale e note resinose di pino. Il profilo West Coast si esprime in un amaro secco, definitivo e prolungato.',
    history:'"United" celebra l\'unione tra la tradizione West Coast californiana e la scena craft italiana. Il doppio dry-hopping massimizza gli aromi senza incrementare l\'amaro percepito.',
    tried:false, favorite:false, notes:'' },
  { name:'Man Bassa', brewery:'50&50 Craft Brewery', category:'pilsner', rating:0, abv:5.0, ibu:35,
    origin:'Varese, Italia', color:'Paglierina dorata limpida, testa bianca abbondante',
    description:'Pilsner di riferimento del birrificio: equilibrata, di grande bevibilità. Luppoli nobili Saaz conferiscono l\'aroma speziato e floreale tipico della tradizione boema.',
    history:'"Man Bassa" è espressione colloquiale lombarda per indicare qualcosa di travolgente. Con una valutazione media di 4.56/5, il nome si è rivelato profetico.',
    tried:false, favorite:false, notes:'' },
  { name:'Graziella', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.5, ibu:15,
    origin:'Varese, Italia', color:'Dorata ambrata con riflessi vinosi, testa fine e persistente',
    description:'Italian Grape Lager prodotta con mosto d\'uva. Note di frutta bianca, pesca e agrumi si fondono con la pulizia della fermentazione lager. Dolcezza vinosa soffusa, finale secco.',
    history:'L\'Italian Grape Lager è uno stile inventato in Italia riconosciuto dalla guida BJCP. Graziella porta in lattina i vigneti lombardi: ibrido perfetto tra birreria e viticoltura.',
    tried:false, favorite:false, notes:'' },
  { name:'Nelson³', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:6.5, ibu:45,
    origin:'Varese, Italia', color:'Dorata intensa con leggera velatura, testa bianca abbondante',
    description:'New Zealand IPA interamente costruita sul luppolo Nelson Sauvin neozelandese, utilizzato in tripla dose. Esplosione aromatica di uva bianca, passion fruit e ribes. Corpo medio, amaro fresco e pulito.',
    history:'Nelson Sauvin è il luppolo emblema della Nuova Zelanda, noto per un profilo che ricorda il Sauvignon Blanc. 50&50 ne esalta le caratteristiche attraverso una tripla aggiunta.',
    tried:false, favorite:false, notes:'' },
  { name:'Slomo', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.0, ibu:60,
    origin:'Varese, Italia', color:'Dorata brillante con leggera velatura, testa bianca fine',
    description:'New Zealand IPL (India Pale Lager): la precisione della fermentazione lager al servizio dell\'intensità luppolata neozelandese. Aroma vivace di frutta tropicale, kiwi e agrumi.',
    history:'"Slomo" descrive la lenta fermentazione a basse temperature. L\'IPL è uno stile ibrido: processo lager, spirito IPA.',
    tried:false, favorite:false, notes:'' },
  { name:'Bosco 21030', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.0, ibu:20,
    origin:'Varese, Italia', color:'Ambrata rame con sfumature miele, testa avorio',
    description:'Chestnut Lager prodotta con farina di castagne, ingrediente tipico dell\'entroterra varesino. Aroma avvolgente di castagne arrostite, nocciola e biscotto.',
    history:'Il CAP 21030 identifica i comuni della Valceresio, area boschiva e castanicola a pochi km da Varese. I castagneti diventano ingrediente vivo in questa lager.',
    tried:false, favorite:false, notes:'' },
  { name:'Crisp', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:5.0, ibu:32,
    origin:'Varese, Italia', color:'Dorata con riflessi ambrati, testa bianca fine',
    description:'Belgian Ale dal carattere elegante e beverino. Profumi floreali e fruttati tipici dei lieviti belgi, con note di agrumi e erbe aromatiche. Corpo medio, carbonazione vivace, finale secco.',
    history:'50&50 nasce dalla passione di due soci al 50% ciascuno. Crisp rappresenta la loro lettura della tradizione belga: lieviti d\'importazione, ingredienti locali.',
    tried:false, favorite:false, notes:'' },
  { name:'Janie Jones', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.8, ibu:25,
    origin:'Varese, Italia', color:'Ambrata chiara, testa bianca compatta',
    description:'English IPA dalla personalità equilibrata e raffinata. Luppoli inglesi tradizionali regalano note erbacee, bergamotto e marmellata d\'arancia. L\'amaro è elegante, mai aggressivo.',
    history:'Janie Jones è il titolo che apre il debut album dei The Clash (1977). 50&50 celebra la cultura UK con una birra che richiama i pub londinesi.',
    tried:false, favorite:false, notes:'' },
  { name:'Bee Serious', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.5, ibu:20,
    origin:'Varese, Italia', color:'Dorata ambrata brillante con testa color miele',
    description:'Honey Lager che unisce la pulizia della fermentazione lager all\'aromaticità delicata del miele naturale. Note floreali e di nettare, corpo morbido e rotondo.',
    history:'Il nome gioca sul doppio senso inglese "Bee" (ape) e "Be" (sii). Utilizza miele locale della zona varesina.',
    tried:false, favorite:false, notes:'' },
  { name:'Drama', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:5.2, ibu:0,
    origin:'Varese, Italia', color:'Bruno scuro con riflessi rubino, testa beige persistente',
    description:'Tmavý Ležák, ovvero la lager scura boema per eccellenza. Malti scuri e Vienna conferiscono note di pane tostato, caramello e cioccolato al latte.',
    history:'"Tmavý Ležák" significa "lager scura" in ceco. 50&50 porta il carattere di Praga sulle rive del Lago di Varese.',
    tried:false, favorite:false, notes:'' },
  { name:'Frank You', brewery:'50&50 Craft Brewery', category:'other', rating:0, abv:5.3, ibu:22,
    origin:'Varese, Italia', color:'Ambrata con riflessi ramati, testa compatta',
    description:'Rauch Beer: la birra affumicata tedesca in versione 50&50. Il malto affumicato al legno di faggio dona aromi di prosciutto crudo e fumo dolce.',
    history:'Le Rauchbier nascono a Bamberga, Franconia. "Frank You" è un gioco di parole: Franconia (Frank) incontra il ringraziamento ironico.',
    tried:false, favorite:false, notes:'' },
  { name:'Kellerona', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:5.0, ibu:15,
    origin:'Varese, Italia', color:'Dorata torbida non filtrata, testa bianca abbondante',
    description:'Kellerbier non filtrata. Erbaceo e floreale all\'aroma, con note di lievito fresco e grano. Morbida, dissetante, con carbonazione contenuta.',
    history:'"Keller" (cantina in tedesco) indica una birra non filtrata. La "-ona" finale è il suffisso italiano accrescitivo affettuoso.',
    tried:false, favorite:false, notes:'' },
  { name:'McBlack', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:8.0, ibu:25,
    origin:'Varese, Italia', color:'Mogano scuro quasi nero, testa beige persistente',
    description:'Scotch Ale dall\'anima forte e avvolgente. Malti scuri tostati con note di cioccolato fondente, caramello bruciato e prugna. Birra da meditazione.',
    history:'"Mc" è il prefisso scozzese per eccellenza. La Scotch Ale (Wee Heavy) è progettata per riscaldare nei climi rigidi.',
    tried:false, favorite:false, notes:'' },
  { name:'Cowboy Kirk', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.5, ibu:45,
    origin:'Varese, Italia', color:'Nera con riflessi bruni, testa cremosa nocciola',
    description:'Black IPA che fonde l\'intensità del malto torrefatto con l\'aggressività luppolata americana. Aroma di caffè, cioccolato fondente e resina.',
    history:'La Black IPA rompe le regole, mescolando tradizione inglese e aggressività americana. Cowboy Kirk è un fuorilegge che non rispetta le categorie.',
    tried:false, favorite:false, notes:'' },
  { name:'Italian Pils', brewery:'50&50 Craft Brewery', category:'pilsner', rating:0, abv:4.5, ibu:35,
    origin:'Varese, Italia', color:'Paglierina brillante, testa bianca fine e persistente',
    description:'Interpretazione italiana dello stile pilsner: luppoli italiani conferiscono un aroma floreale e speziato insolito rispetto alla tradizione boema.',
    history:'L\'Italian Pils reinterpreta la tradizione con luppoli autoctoni italiani. 50&50 abbraccia questa corrente con convinzione.',
    tried:false, favorite:false, notes:'' },
  { name:'Better Call Welly', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:4.2, ibu:0,
    origin:'Varese, Italia', color:'Ambrata ramata, testa avorio compatta',
    description:'English Bitter di facile bevibilità, omaggio alla tradizione dei pub britannici. Maltatura biscottata e caramellata, luppoli erbacei e terrosi.',
    history:'"Better Call Welly" rimanda alla cultura pub inglese dove il Bitter è la birra per eccellenza. Bassa gradazione, alta bevibilità.',
    tried:false, favorite:false, notes:'' },
  { name:'8.6 Red', brewery:'Bavaria N.V.', category:'ale', rating:0, abv:7.9, ibu:20,
    origin:'Veghel, Paesi Bassi', color:'Rosso rubino intenso con riflessi ambrati, testa bianco-rosata fine',
    description:'Intense Red Beer ad alta gradazione alcolica. Aroma maltato complesso con note di caramello, frutta rossa matura e lieve speziatura. Corpo pieno e rotondo; la dolcezza dei malti caramellati è controbilanciata da un amaro moderato e da un finale pulito. Vincitrice del World Beer Awards Gold.',
    history:'Il nome "8.6" nasce dalla gradazione originale della birra capostipite. La variante Red estende la gamma verso uno stile Red Ale di carattere, puntando su malti speciali che conferiscono il colore rubino intenso. Realizzata da Bavaria N.V., secondo produttore olandese per volume, viene commercializzata nei mercati internazionali con la dicitura "Imported from Holland".',
    tried:false, favorite:false, notes:'' },
  { name:'Kozel Premium', brewery:'Pivovar Velké Popovice', category:'lager', rating:0, abv:4.6, ibu:22,
    origin:'Velké Popovice, Repubblica Ceca', color:'Dorata brillante con riflessi paglierini, testa bianca compatta e persistente',
    description:'Světlý ležák (pale lager ceca) di grande tradizione. I malti Moravia conferiscono note di pane fresco e biscotto; il luppolo Saaz aggiunge una speziatura erbacea e floreale tipicamente boema. Corpo medio-leggero, carbonazione vivace e finale secco e pulito che invita al sorso successivo.',
    history:'Kozel — "capro" in ceco — prende il nome dalla capra simbolo del birrificio di Velké Popovice, fondato nel 1874 a pochi chilometri da Praga. La leggenda vuole che una capra di nome Franciszek abitasse le cantine del birrificio portando fortuna ai mastri birrai. Oggi di proprietà del gruppo Molson Coors, Kozel Premium è una delle lager ceche più esportate al mondo.',
    tried:false, favorite:false, notes:'' },
];
