// ═══════════════════════════════════════════════════════════
// DATA & CONSTANTS
// ═══════════════════════════════════════════════════════════

export const CATEGORIES = [
  { id:'lager',      name:'Lager',              color:'#D4A017' },
  { id:'ale',        name:'Ale',                color:'#D4882E' },
  { id:'ipa',        name:'IPA',                color:'#6B8F3E' },
  { id:'stout',      name:'Stout & Porter',     color:'#A08060' },
  { id:'weizen',     name:'Weizen & Blanche',   color:'#C8A84B' },
  { id:'sour',       name:'Sour & Lambic',      color:'#B5A014' },
  { id:'trappist',   name:'Trappista & Abbey',  color:'#8B4513' },
  { id:'pilsner',    name:'Pilsner',             color:'#C8B400' },
  { id:'saison',     name:'Saison & Farmhouse', color:'#D4A856' },
  { id:'barleywine', name:'Barleywine',         color:'#8B2020' },
  { id:'radler',     name:'Radler & Shandy',    color:'#E8952E' },
  { id:'other',      name:'Altro',              color:'#9E7B5A' },
];

export const CAT_MAP = Object.fromEntries(CATEGORIES.map(c => [c.id, c]));

export const SAMPLE_BEERS = [
  // ── 50&50 Craft Brewery ─────────────────────────────────
  { name:'Kalopsia', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.6, ibu:45,
    origin:'Varese, Italia', color:'Ambrata chiara limpida, testa bianca cremosa',
    description:'APA (American Pale Ale) flagship del birrificio. Luppoli americani Cascade e Centennial donano classici aromi di pompelmo, resina e fiori d\'arancio. Maltatura caramellata presente ma discreta, a supporto dell\'amaro bilanciato e persistente.',
    history:'"Kalopsia" in greco antico significa "visione distorta di bellezza". È la birra che ha lanciato il birrificio: con oltre 400 recensioni entusiaste è diventata l\'identità di 50&50, una piccola grande ossessione varesina.',
    tried:false, favorite:false, notes:'' },
  { name:'Danko', brewery:'50&50 Craft Brewery', category:'stout', rating:0, abv:8.0, ibu:30,
    origin:'Varese, Italia', color:'Nero profondo con riflessi bruni, testa beige compatta',
    description:'Imperial Baltic Porter di forza e complessità notevoli. Un fantastico viaggio tra datteri, sentori di resine e toffee, traghettati sul finale dal cacao e note di caffè. La fermentazione lager garantisce una pulizia straordinaria. Alcol perfettamente integrato.',
    history:'"Danko" omaggia il personaggio mitologico slavo che strappò il proprio cuore ardente dal petto per illuminare il cammino del suo popolo. Una delle birre più amate del catalogo 50&50.',
    tried:false, favorite:false, notes:'' },
  { name:'Django', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:7.0, ibu:70,
    origin:'Varese, Italia', color:'Ambrata con riflessi ramati, testa bianca compatta',
    description:'American IPA di carattere deciso. Un\'esplosione di frutta tropicale bilanciata da note di caramello e resina. Una vera spremuta di luppolo, intensa e appagante. La birra più recensita del birrificio.',
    history:'Django è la birra che ha fatto conoscere 50&50 al grande pubblico craft italiano, con oltre 700 recensioni su Untappd. Il nome evoca il cinema spaghetti-western e lo spirito ribelle del birrificio varesino.',
    tried:false, favorite:false, notes:'' },
  { name:'Dr. Shultz', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:6.5, ibu:60,
    origin:'Varese, Italia', color:'Dorata brillante, testa bianca fine',
    description:'American IPA dal colore dorato. Presenta aromi agrumati e tropicali che ben si bilanciano con il gusto del malto. Il classico che non ti stanca: luppolatura generosa ma mai aggressiva.',
    history:'Il nome omaggia il personaggio del Dr. King Schultz dal film "Django Unchained" di Tarantino, compagno ideale della Django del birrificio. Con oltre 640 recensioni, è una delle IPA più apprezzate di 50&50.',
    tried:false, favorite:false, notes:'' },
  { name:'United', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.8, ibu:40,
    origin:'Varese, Italia', color:'Ambrata dorata brillante, testa bianca compatta',
    description:'IPA freschissima fatta con solo malto Pils e generosamente luppolata con Mosaic e Simcoe. Le note tropicali si mischiano a quelle floreali e agrumate. Birra di facile bevuta con una piacevole nota maltata seguita dai sentori di luppolo. Finale piacevolmente amaro.',
    history:'"United" celebra l\'unione tra la tradizione West Coast californiana e la scena craft italiana. Il doppio dry-hopping massimizza gli aromi senza incrementare l\'amaro percepito.',
    tried:false, favorite:false, notes:'' },
  { name:'Man Bassa', brewery:'50&50 Craft Brewery', category:'pilsner', rating:0, abv:5.0, ibu:35,
    origin:'Varese, Italia', color:'Paglierina dorata limpida, testa bianca abbondante',
    description:'Pilsner boema di riferimento del birrificio. Il profumo di erba appena tagliata si fonde a quello dolce del malto Pils creando un equilibrio perfetto. Equilibrata, di grande bevibilità.',
    history:'"Man Bassa" è espressione colloquiale lombarda per indicare qualcosa di travolgente. Il primo amore non si scorda mai: con oltre 440 recensioni, il nome si è rivelato profetico.',
    tried:false, favorite:false, notes:'' },
  { name:'Mr. Crocodile', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:4.5, ibu:40,
    origin:'Varese, Italia', color:'Dorata chiara limpida, testa bianca fine e persistente',
    description:'India Pale Lager chiara e dissetante. I luppoli australiani donano profumi e sapori tropicali accompagnati da sentori di agrume e resinoso. Pericolosamente beverina grazie alla bassa gradazione e alla pulizia della fermentazione lager.',
    history:'Mr. Crocodile unisce la precisione della lager all\'intensità luppolata di un\'IPA, utilizzando luppoli dall\'emisfero australe. Un coccodrillo in agguato: sembra innocua, ma ha carattere da vendere.',
    tried:false, favorite:false, notes:'' },
  { name:'Effimera', brewery:'50&50 Craft Brewery', category:'trappist', rating:0, abv:9.0, ibu:23,
    origin:'Varese, Italia', color:'Aranciata carica con riflessi dorati, testa bianca cremosa',
    description:'Belgian Tripel dal colore aranciato carico. Sentori maltati e fruttati si bilanciano, lasciando spazio a un finale secco e pulito. Una regina: corpo pieno, alcol perfettamente integrato, carbonazione vivace.',
    history:'La Tripel è lo stile monastico belga per eccellenza. Effimera cattura la fugace perfezione di un momento: una birra che esiste solo nel qui e ora, da gustare con reverenza.',
    tried:false, favorite:false, notes:'' },
  { name:'Graziella', brewery:'50&50 Craft Brewery', category:'other', rating:0, abv:6.5, ibu:15,
    origin:'Varese, Italia', color:'Dorata ambrata con riflessi vinosi, testa fine e persistente',
    description:'Italian Grape Ale prodotta con il 12% di mosto di uve Moscato. Note di frutta bianca, pesca e agrumi si fondono con la pulizia della fermentazione lager. Dolcezza vinosa soffusa, finale secco.',
    history:'L\'Italian Grape Ale è uno stile inventato in Italia riconosciuto dalla guida BJCP. "Grazia, Graziella e grazie a Ciro": il nome è un omaggio ironico che porta in lattina i vigneti lombardi.',
    tried:false, favorite:false, notes:'' },
  { name:'Nelson³', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:6.5, ibu:45,
    origin:'Varese, Italia', color:'Dorata intensa con leggera velatura, testa bianca abbondante',
    description:'New Zealand IPA interamente costruita sul luppolo Nelson Sauvin neozelandese, utilizzato in tripla dose. Esplosione aromatica di uva bianca, passion fruit e ribes. Corpo medio, amaro fresco e pulito.',
    history:'Nelson Sauvin è il luppolo emblema della Nuova Zelanda, noto per un profilo che ricorda il Sauvignon Blanc. 50&50 ne esalta le caratteristiche attraverso una tripla aggiunta.',
    tried:false, favorite:false, notes:'' },
  { name:'Slo Mo', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:5.0, ibu:40,
    origin:'Varese, Italia', color:'Dorata brillante con leggera velatura, testa bianca fine e compatta',
    description:'India Pale Lager protagonista assoluta dei luppoli Nelson Sauvin e HBC 586. Esplosione di agrumi freschi e frutta tropicale: pompelmo, lime, mango e un accenno di uva spina. Al primo sorso sembra quasi morbida, poi l\'amaro pulito e deciso entra in gioco, bilanciato da una base maltata discreta ma efficace.',
    history:'"Slo Mo" descrive la lenta fermentazione a basse temperature del lievito W34-70, che lascia un finale secco e pulito. L\'IPL è uno stile ibrido: processo lager, spirito IPA. Una birra che inganna con la sua facilità di bevuta.',
    tried:false, favorite:false, notes:'' },
  { name:'Bosco 21030', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.0, ibu:20,
    origin:'Varese, Italia', color:'Ambrata rame con sfumature miele, testa avorio',
    description:'Chestnut Lager prodotta con farina di castagne, ingrediente tipico dell\'entroterra varesino. Aroma avvolgente di castagne arrostite, nocciola e biscotto.',
    history:'Il CAP 21030 identifica i comuni della Valceresio, area boschiva e castanicola a pochi km da Varese. I castagneti diventano ingrediente vivo in questa lager.',
    tried:false, favorite:false, notes:'' },
  { name:'Crisp', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:5.0, ibu:32,
    origin:'Varese, Italia', color:'Dorata con riflessi ambrati, testa bianca fine',
    description:'Belgian Ale dal carattere elegante e beverino. Profumi floreali e fruttati tipici dei lieviti belgi, con note di agrumi e erbe aromatiche. Corpo medio, carbonazione vivace, finale secco.',
    history:'50&50 nasce dalla passione di due soci al 50% ciascuno. Crisp rappresenta la loro lettura della tradizione belga: lieviti d\'importazione, ingredienti locali.',
    tried:false, favorite:false, notes:'' },
  { name:'Janie Jones', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.8, ibu:25,
    origin:'Varese, Italia', color:'Ambrata chiara, testa bianca compatta',
    description:'English IPA dalla personalità equilibrata e raffinata. Luppoli inglesi tradizionali regalano note erbacee, bergamotto e marmellata d\'arancia. L\'amaro è elegante, mai aggressivo.',
    history:'Janie Jones è il titolo che apre il debut album dei The Clash (1977). 50&50 celebra la cultura UK con una birra che richiama i pub londinesi.',
    tried:false, favorite:false, notes:'' },
  { name:'Bee Serious', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.5, ibu:20,
    origin:'Varese, Italia', color:'Dorata ambrata brillante con testa color miele',
    description:'Honey Lager che unisce la pulizia della fermentazione lager all\'aromaticità delicata del miele naturale. Note floreali e di nettare, corpo morbido e rotondo.',
    history:'Il nome gioca sul doppio senso inglese "Bee" (ape) e "Be" (sii). Utilizza miele locale della zona varesina.',
    tried:false, favorite:false, notes:'' },
  { name:'Drama', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:5.2, ibu:0,
    origin:'Varese, Italia', color:'Bruno scuro con riflessi rubino, testa beige persistente',
    description:'Tmavý Ležák, ovvero la lager scura boema per eccellenza. Malti scuri e Vienna conferiscono note di pane tostato, caramello e cioccolato al latte.',
    history:'"Tmavý Ležák" significa "lager scura" in ceco. 50&50 porta il carattere di Praga sulle rive del Lago di Varese.',
    tried:false, favorite:false, notes:'' },
  { name:'Frank You', brewery:'50&50 Craft Brewery', category:'other', rating:0, abv:5.3, ibu:22,
    origin:'Varese, Italia', color:'Ambrata con riflessi ramati, testa compatta',
    description:'Rauch Beer: la birra affumicata tedesca in versione 50&50. Il malto affumicato al legno di faggio dona aromi di prosciutto crudo e fumo dolce.',
    history:'Le Rauchbier nascono a Bamberga, Franconia. "Frank You" è un gioco di parole: Franconia (Frank) incontra il ringraziamento ironico.',
    tried:false, favorite:false, notes:'' },
  { name:'Kellerona', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:5.0, ibu:15,
    origin:'Varese, Italia', color:'Dorata torbida non filtrata, testa bianca abbondante',
    description:'Kellerbier non filtrata. Erbaceo e floreale all\'aroma, con note di lievito fresco e grano. Morbida, dissetante, con carbonazione contenuta.',
    history:'"Keller" (cantina in tedesco) indica una birra non filtrata. La "-ona" finale è il suffisso italiano accrescitivo affettuoso.',
    tried:false, favorite:false, notes:'' },
  { name:'Mc Black', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:8.0, ibu:25,
    origin:'Varese, Italia', color:'Mogano scuro quasi nero, testa beige persistente',
    description:'Scotch Ale (Wee Heavy) dall\'anima forte e avvolgente. Malti scuri tostati con note di cioccolato fondente, caramello bruciato e prugna. Birra da meditazione.',
    history:'"Mc" è il prefisso scozzese per eccellenza. La Scotch Ale è progettata per riscaldare nei climi rigidi: 50&50 porta le Highlands sulle prealpi varesine.',
    tried:false, favorite:false, notes:'' },
  { name:'Cowboy Kirk', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:5.5, ibu:45,
    origin:'Varese, Italia', color:'Nera con riflessi bruni, testa cremosa nocciola',
    description:'Black IPA che fonde l\'intensità del malto torrefatto con l\'aggressività luppolata americana. Aroma di caffè, cioccolato fondente e resina.',
    history:'La Black IPA rompe le regole, mescolando tradizione inglese e aggressività americana. Cowboy Kirk è un fuorilegge che non rispetta le categorie.',
    tried:false, favorite:false, notes:'' },
  { name:'Italian Pils', brewery:'50&50 Craft Brewery', category:'pilsner', rating:0, abv:4.5, ibu:35,
    origin:'Varese, Italia', color:'Paglierina brillante, testa bianca fine e persistente',
    description:'Interpretazione italiana dello stile pilsner con luppolo Diamant in dry hopping. Aroma floreale e speziato insolito rispetto alla tradizione boema, con una freschezza tutta italiana.',
    history:'L\'Italian Pils reinterpreta la tradizione con luppoli autoctoni italiani. 50&50 abbraccia questa corrente con convinzione.',
    tried:false, favorite:false, notes:'' },
  { name:'Better Call Welly', brewery:'50&50 Craft Brewery', category:'ale', rating:0, abv:4.2, ibu:0,
    origin:'Varese, Italia', color:'Ambrata ramata, testa avorio compatta',
    description:'English Bitter di facile bevibilità, omaggio alla tradizione dei pub britannici. Maltatura biscottata e caramellata, luppoli erbacei e terrosi.',
    history:'"Better Call Welly" rimanda alla cultura pub inglese dove il Bitter è la birra per eccellenza. Bassa gradazione, alta bevibilità.',
    tried:false, favorite:false, notes:'' },
  { name:'Bebop', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:6.8, ibu:25,
    origin:'Varese, Italia', color:'Ramata carica con riflessi ambrati, testa avorio compatta',
    description:'Bock tradizionale dal colore ramato carico. Caramello e cereali si rincorrono supportati da una nota fresca di luppolo tedesco. Corpo pieno e maltato, finale pulito e asciutto.',
    history:'La Bock è lo stile forte bavarese per eccellenza. Bebop unisce la potenza della tradizione tedesca al ritmo del jazz: una birra che improvvisa sul tema dei malti.',
    tried:false, favorite:false, notes:'' },
  { name:'Alus', brewery:'50&50 Craft Brewery', category:'lager', rating:0, abv:4.8, ibu:14,
    origin:'Varese, Italia', color:'Bionda dorata brillante, testa bianca abbondante',
    description:'Helles Lager dove profumi di malto si mescolano a una leggera nota erbacea. Rotonda con un finale asciutto. Chiudi gli occhi, sei a Monaco! La quintessenza della bevibilità.',
    history:'"Alus" in lituano significa semplicemente "birra". Una Helles cristallina che riporta alle birrerie di Monaco di Baviera, dove la semplicità è la forma più alta di maestria.',
    tried:false, favorite:false, notes:'' },
  { name:'God of Laif', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:4.5, ibu:40,
    origin:'Varese, Italia', color:'Dorata con leggera velatura, testa bianca fine',
    description:'Session IPA pulita e secca, luppolata con Eclipse. Aromi freschi e agrumati per una birra che invita al sorso successivo senza stancare. Leggera ma con carattere luppolato definito.',
    history:'Realizzata in collaborazione con Yeast Cost Bar & Organic Lab. "Che sto a fa? Sto a fa a laif" — una Session IPA per evadere dal solito sapore, con lo spirito scanzonato che contraddistingue 50&50.',
    tried:false, favorite:false, notes:'' },
  { name:'Silvio\'s', brewery:'50&50 Craft Brewery', category:'stout', rating:0, abv:5.2, ibu:0,
    origin:'Varese, Italia', color:'Nera con riflessi mogano, testa beige cremosa persistente',
    description:'Oatmeal Stout vellutata e avvolgente. L\'avena conferisce un corpo setoso e cremoso, con note di cioccolato al latte, caffè e biscotto di cereali. Amaro contenuto, finale dolce e tostato.',
    history:'L\'Oatmeal Stout è la stout da tutti i giorni: nutriente, confortante, bevibile. Silvio\'s porta il calore di un pub inglese nel cuore della Lombardia.',
    tried:false, favorite:false, notes:'' },
  { name:'Screamer', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:8.5, ibu:70,
    origin:'Varese, Italia', color:'Dorata ambrata intensa, testa bianca persistente',
    description:'Triple Dry-Hopped Double IPA invernale. Luppolatura estrema e potenza alcolica si fondono in un\'esplosione aromatica di agrumi, resina e frutta tropicale. Corpo pieno, amaro imponente ma equilibrato.',
    history:'"Cold weather TDH DIPA" — Screamer è la birra che urla d\'inverno. Una DIPA pensata per le serate fredde, dove il triplo dry-hopping e gli 8.5% ABV riscaldano corpo e spirito.',
    tried:false, favorite:false, notes:'' },
  { name:'Hangman', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:8.5, ibu:0,
    origin:'Varese, Italia', color:'Dorata intensa con velatura, testa bianca compatta',
    description:'Imperial / Double IPA di grande intensità. Luppolatura massiccia con profilo aromatico tropicale e resinoso. Corpo pieno e rotondo, alcol ben integrato. Una DIPA che non fa prigionieri.',
    history:'Hangman — il boia — è una DIPA che giustizia ogni aspettativa. Con una media di 3.88 su Untappd, è una delle birre più apprezzate del catalogo 50&50 per potenza e complessità.',
    tried:false, favorite:false, notes:'' },
  { name:'Double God', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:7.5, ibu:0,
    origin:'Varese, Italia', color:'Dorata carica con leggera velatura, testa bianca cremosa',
    description:'Imperial / Double IPA evoluzione della God of Laif. Stessa filosofia Session amplificata: luppolatura raddoppiata, corpo più pieno, intensità aromatica tropicale e agrumata al massimo.',
    history:'Double God è la versione potenziata della God of Laif: dal 4.5% al 7.5% ABV, un salto di fede luppolato. Il "dio" della birra artigianale varesina in versione suprema.',
    tried:false, favorite:false, notes:'' },
  { name:'How Much Hops Is Too Much Hops', brewery:'50&50 Craft Brewery', category:'ipa', rating:0, abv:7.0, ibu:40,
    origin:'Varese, Italia', color:'Gialla opaca con velatura intensa, testa bianca soffice',
    description:'New England / Hazy IPA che risponde alla domanda nel nome: il luppolo non è mai troppo. Torbida e succosa, con esplosione di frutta tropicale, pesca e mango. Amaro morbido e avvolgente, corpo pieno e vellutato.',
    history:'Il nome è un manifesto: quanto luppolo è troppo luppolo? Per 50&50 la risposta è chiara — non esiste un limite. Con una media di 3.86 su Untappd, è la Hazy IPA di riferimento del birrificio.',
    tried:false, favorite:false, notes:'' },
  { name:'L\'Encompètant', brewery:'50&50 Craft Brewery', category:'saison', rating:0, abv:3.8, ibu:18,
    origin:'Varese, Italia', color:'Dorata chiara con leggera velatura, testa bianca fine',
    description:'Saison belga atipica in versione session. Lieviti belgi donano note fruttate e speziate, con un corpo leggero e un finale secco e dissetante. Carbonazione vivace e grande bevibilità.',
    history:'"L\'Encompètant" è una Saison Session atipica che rompe gli schemi della tradizione belga. Con soli 3.8% ABV dimostra che la complessità non richiede necessariamente gradazione alcolica.',
    tried:false, favorite:false, notes:'' },
  { name:'JOLENE', brewery:'50&50 Craft Brewery', category:'saison', rating:0, abv:6.5, ibu:25,
    origin:'Varese, Italia', color:'Dorata con riflessi ambrati, testa bianca fine e persistente',
    description:'Saison rifermentata in tank con l\'aggiunta di Brettanomyces durante il confezionamento. Note funky e fruttate tipiche del Brett si sommano al carattere speziato e secco della Saison. Complessità in evoluzione.',
    history:'"Road to Belgium!" — JOLENE è la prima Saison di 50&50, un viaggio verso la tradizione farmhouse belga. Il Brettanomyces aggiunge una dimensione selvatica che evolve nel tempo.',
    tried:false, favorite:false, notes:'' },
  { name:'Ox & Donkey', brewery:'50&50 Craft Brewery', category:'stout', rating:0, abv:10.0, ibu:30,
    origin:'Varese, Italia', color:'Nero impenetrabile con testa beige cremosa',
    description:'Imperial Pastry Stout con cacao e vaniglia, realizzata in collaborazione con Zona Mosto. Corpo denso e avvolgente, dolcezza controllata, note intense di cioccolato fondente e vaniglia bourbon. Un dessert liquido.',
    history:'Ox & Donkey è una collaborazione natalizia con Zona Mosto. Con una media di 3.95 su Untappd — la più alta del catalogo — è la prova che 50&50 eccelle anche nelle birre estreme.',
    tried:false, favorite:false, notes:'' },
  { name:'Fragole Panna & Ch*mp*gne', brewery:'50&50 Craft Brewery', category:'sour', rating:0, abv:3.8, ibu:0,
    origin:'Varese, Italia', color:'Rosa intenso con testa rosata fine',
    description:'Smoothie / Pastry Sour con fragole e panna. Acidità fresca e fruttata, corpo leggero e cremoso. Note intense di fragola fresca, con un finale pulito e dissetante. Una birra-dessert estiva.',
    history:'Il nome censurato giocosamente nasconde lo "Champagne". Una Sour golosa e leggera che sfida le convenzioni: fragole, panna e bollicine nello spirito irriverente di 50&50.',
    tried:false, favorite:false, notes:'' },
  { name:'8.6 Red', brewery:'Bavaria N.V.', category:'ale', rating:0, abv:7.9, ibu:20,
    origin:'Veghel, Paesi Bassi', color:'Rosso rubino intenso con riflessi ambrati, testa bianco-rosata fine',
    description:'Intense Red Beer ad alta gradazione alcolica. Aroma maltato complesso con note di caramello, frutta rossa matura e lieve speziatura. Corpo pieno e rotondo; la dolcezza dei malti caramellati è controbilanciata da un amaro moderato e da un finale pulito. Vincitrice del World Beer Awards Gold.',
    history:'Il nome "8.6" nasce dalla gradazione originale della birra capostipite. La variante Red estende la gamma verso uno stile Red Ale di carattere, puntando su malti speciali che conferiscono il colore rubino intenso. Realizzata da Bavaria N.V., secondo produttore olandese per volume, viene commercializzata nei mercati internazionali con la dicitura "Imported from Holland".',
    tried:false, favorite:false, notes:'' },
  { name:'Kozel Premium', brewery:'Pivovar Velké Popovice', category:'lager', rating:0, abv:4.6, ibu:22,
    origin:'Velké Popovice, Repubblica Ceca', color:'Dorata brillante con riflessi paglierini, testa bianca compatta e persistente',
    description:'Světlý ležák (pale lager ceca) di grande tradizione. I malti Moravia conferiscono note di pane fresco e biscotto; il luppolo Saaz aggiunge una speziatura erbacea e floreale tipicamente boema. Corpo medio-leggero, carbonazione vivace e finale secco e pulito che invita al sorso successivo.',
    history:'Kozel — "capro" in ceco — prende il nome dalla capra simbolo del birrificio di Velké Popovice, fondato nel 1874 a pochi chilometri da Praga. La leggenda vuole che una capra di nome Franciszek abitasse le cantine del birrificio portando fortuna ai mastri birrai. Oggi di proprietà del gruppo Molson Coors, Kozel Premium è una delle lager ceche più esportate al mondo.',
    tried:false, favorite:false, notes:'' },
];
